# ===Services===
services:
  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/wordpress
    networks:
      - Inception.net
    depends_on:
      - wordpress
    restart: always
  mariadb: 
    image: mariadb
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - wp_database:/var/lib/mysql
    networks:
      - Inception.net
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ROOT_PASS=${DB_ROOT_PASS}
      - DB_USER=${DB_USER}
      - DB_USER_PASS=${DB_USER_PASS}
      
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASS=${DB_USER_PASS}
      - WP_USER=${WP_USER}
      - WP_USER_PASS=${WP_USER_PASS}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
    volumes:
      - wp_files:/var/www/wordpress
    depends_on:
      - mariadb
      - redis
    networks:
      - Inception.net
    restart: always
  # BONUS
  redis:
    image: redis
    container_name: redis
    build: 
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - Inception.net
    restart: always
  ftp :
    image : ftp
    container_name : ftp
    build: 
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    networks:
      - Inception.net
    restart: always
# ===Networks===
networks:
  Inception.net:
    name : Inception.net
    driver: bridge
# ===Volumes===
volumes:
  wp_database:
    name : wp_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zero/data/wp_database
  wp_files:
    name : wp_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zero/data/wp_files
