NAME	= BraiiiiiiinnnzzzZ
	
CC		= c++
FLAGS	= -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): 
	@ $(CC) $(FLAGS) newZombie.cpp randomChump.cpp Zombie.cpp -o $(NAME)

clean:
	rm -rf $(NAME)
fclean:
	rm -rf $(NAME)
re: clean all